name: Residence
main: com.bekvon.bukkit.residence.Residence
version: 0.0.1
description: Cuboid Residence Plugin
author: Silentneeb
softdepend: [Vault,WorldEdit]
commands:
  residence:
    description: Manage Residences
    usage: §c/residence ? for more info
    aliases: [res, resadmin]
  resreload:
    description: Reload the entire residence plugin.
    usage: §c/resreload
  resload:
    description: Load the save file again after you have made modifications.
    usage: §c/resload
  rc:
    description: §cChat in current residence channel.
    usage: §c/rc to toggle, or /rc <message>
  resworld:
    description: §cRemoves every residence in a world.
    usage: §c/resworld remove [world]
  home:
    description: Return to your plot.
    permission: sentials.tp.home
    usage: /home
  visit:
    description: Visit a player's lot.
    permission: sentials.tp.visit
    usage: /visit (player/lot #)
permissions:
  residence.admin:
    description: Gives you access to /resadmin
    default: op
  residence.create:
    description: Allows you to create residences
    default: op
